/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiPublicBootstrapAdminRouteImport } from './routes/api/public/bootstrap-admin'
import { Route as AuthenticatedSupplierReturnsRouteImport } from './routes/_authenticated/supplier.returns'
import { Route as AuthenticatedStockPendingRouteImport } from './routes/_authenticated/stock.pending'
import { Route as AuthenticatedStockMutationsRouteImport } from './routes/_authenticated/stock.mutations'
import { Route as AuthenticatedStockLevelsRouteImport } from './routes/_authenticated/stock.levels'
import { Route as AuthenticatedStockInRouteImport } from './routes/_authenticated/stock.in'
import { Route as AuthenticatedSalaryPaymentRouteImport } from './routes/_authenticated/salary.payment'
import { Route as AuthenticatedSalaryBonusPendingRouteImport } from './routes/_authenticated/salary.bonus-pending'
import { Route as AuthenticatedSalaryBonusRouteImport } from './routes/_authenticated/salary.bonus'
import { Route as AuthenticatedSalaryAdvanceRouteImport } from './routes/_authenticated/salary.advance'
import { Route as AuthenticatedSalaryAccrualKurirRouteImport } from './routes/_authenticated/salary.accrual-kurir'
import { Route as AuthenticatedSalaryAccrualRouteImport } from './routes/_authenticated/salary.accrual'
import { Route as AuthenticatedReportsReturnsRouteImport } from './routes/_authenticated/reports.returns'
import { Route as AuthenticatedReportsReceivablesRouteImport } from './routes/_authenticated/reports.receivables'
import { Route as AuthenticatedReportsPayablesRouteImport } from './routes/_authenticated/reports.payables'
import { Route as AuthenticatedReportsMutationsRouteImport } from './routes/_authenticated/reports.mutations'
import { Route as AuthenticatedReportsExpensesRouteImport } from './routes/_authenticated/reports.expenses'
import { Route as AuthenticatedReportsCashflowRouteImport } from './routes/_authenticated/reports.cashflow'
import { Route as AuthenticatedReportsBonusRouteImport } from './routes/_authenticated/reports.bonus'
import { Route as AuthenticatedPaymentsSupplierRouteImport } from './routes/_authenticated/payments.supplier'
import { Route as AuthenticatedPaymentsPendingRouteImport } from './routes/_authenticated/payments.pending'
import { Route as AuthenticatedPaymentsCustomerRouteImport } from './routes/_authenticated/payments.customer'
import { Route as AuthenticatedMasterWarehousesRouteImport } from './routes/_authenticated/master.warehouses'
import { Route as AuthenticatedMasterSuppliersRouteImport } from './routes/_authenticated/master.suppliers'
import { Route as AuthenticatedMasterProductsRouteImport } from './routes/_authenticated/master.products'
import { Route as AuthenticatedMasterExpenseCategoriesRouteImport } from './routes/_authenticated/master.expense-categories'
import { Route as AuthenticatedMasterEmployeesRouteImport } from './routes/_authenticated/master.employees'
import { Route as AuthenticatedMasterCustomersRouteImport } from './routes/_authenticated/master.customers'
import { Route as AuthenticatedMasterBankAccountsRouteImport } from './routes/_authenticated/master.bank-accounts'
import { Route as ApiPublicV1SplatRouteImport } from './routes/api/public/v1/$'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicBootstrapAdminRoute = ApiPublicBootstrapAdminRouteImport.update({
  id: '/api/public/bootstrap-admin',
  path: '/api/public/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSupplierReturnsRoute =
  AuthenticatedSupplierReturnsRouteImport.update({
    id: '/supplier/returns',
    path: '/supplier/returns',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStockPendingRoute =
  AuthenticatedStockPendingRouteImport.update({
    id: '/stock/pending',
    path: '/stock/pending',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStockMutationsRoute =
  AuthenticatedStockMutationsRouteImport.update({
    id: '/stock/mutations',
    path: '/stock/mutations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStockLevelsRoute =
  AuthenticatedStockLevelsRouteImport.update({
    id: '/stock/levels',
    path: '/stock/levels',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStockInRoute = AuthenticatedStockInRouteImport.update({
  id: '/stock/in',
  path: '/stock/in',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalaryPaymentRoute =
  AuthenticatedSalaryPaymentRouteImport.update({
    id: '/salary/payment',
    path: '/salary/payment',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalaryBonusPendingRoute =
  AuthenticatedSalaryBonusPendingRouteImport.update({
    id: '/salary/bonus-pending',
    path: '/salary/bonus-pending',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalaryBonusRoute =
  AuthenticatedSalaryBonusRouteImport.update({
    id: '/salary/bonus',
    path: '/salary/bonus',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalaryAdvanceRoute =
  AuthenticatedSalaryAdvanceRouteImport.update({
    id: '/salary/advance',
    path: '/salary/advance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalaryAccrualKurirRoute =
  AuthenticatedSalaryAccrualKurirRouteImport.update({
    id: '/salary/accrual-kurir',
    path: '/salary/accrual-kurir',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalaryAccrualRoute =
  AuthenticatedSalaryAccrualRouteImport.update({
    id: '/salary/accrual',
    path: '/salary/accrual',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsReturnsRoute =
  AuthenticatedReportsReturnsRouteImport.update({
    id: '/reports/returns',
    path: '/reports/returns',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsReceivablesRoute =
  AuthenticatedReportsReceivablesRouteImport.update({
    id: '/reports/receivables',
    path: '/reports/receivables',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsPayablesRoute =
  AuthenticatedReportsPayablesRouteImport.update({
    id: '/reports/payables',
    path: '/reports/payables',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsMutationsRoute =
  AuthenticatedReportsMutationsRouteImport.update({
    id: '/reports/mutations',
    path: '/reports/mutations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsExpensesRoute =
  AuthenticatedReportsExpensesRouteImport.update({
    id: '/reports/expenses',
    path: '/reports/expenses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsCashflowRoute =
  AuthenticatedReportsCashflowRouteImport.update({
    id: '/reports/cashflow',
    path: '/reports/cashflow',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsBonusRoute =
  AuthenticatedReportsBonusRouteImport.update({
    id: '/reports/bonus',
    path: '/reports/bonus',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsSupplierRoute =
  AuthenticatedPaymentsSupplierRouteImport.update({
    id: '/payments/supplier',
    path: '/payments/supplier',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsPendingRoute =
  AuthenticatedPaymentsPendingRouteImport.update({
    id: '/payments/pending',
    path: '/payments/pending',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsCustomerRoute =
  AuthenticatedPaymentsCustomerRouteImport.update({
    id: '/payments/customer',
    path: '/payments/customer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterWarehousesRoute =
  AuthenticatedMasterWarehousesRouteImport.update({
    id: '/master/warehouses',
    path: '/master/warehouses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterSuppliersRoute =
  AuthenticatedMasterSuppliersRouteImport.update({
    id: '/master/suppliers',
    path: '/master/suppliers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterProductsRoute =
  AuthenticatedMasterProductsRouteImport.update({
    id: '/master/products',
    path: '/master/products',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterExpenseCategoriesRoute =
  AuthenticatedMasterExpenseCategoriesRouteImport.update({
    id: '/master/expense-categories',
    path: '/master/expense-categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterEmployeesRoute =
  AuthenticatedMasterEmployeesRouteImport.update({
    id: '/master/employees',
    path: '/master/employees',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterCustomersRoute =
  AuthenticatedMasterCustomersRouteImport.update({
    id: '/master/customers',
    path: '/master/customers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterBankAccountsRoute =
  AuthenticatedMasterBankAccountsRouteImport.update({
    id: '/master/bank-accounts',
    path: '/master/bank-accounts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicV1SplatRoute = ApiPublicV1SplatRouteImport.update({
  id: '/api/public/v1/$',
  path: '/api/public/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/master/bank-accounts': typeof AuthenticatedMasterBankAccountsRoute
  '/master/customers': typeof AuthenticatedMasterCustomersRoute
  '/master/employees': typeof AuthenticatedMasterEmployeesRoute
  '/master/expense-categories': typeof AuthenticatedMasterExpenseCategoriesRoute
  '/master/products': typeof AuthenticatedMasterProductsRoute
  '/master/suppliers': typeof AuthenticatedMasterSuppliersRoute
  '/master/warehouses': typeof AuthenticatedMasterWarehousesRoute
  '/payments/customer': typeof AuthenticatedPaymentsCustomerRoute
  '/payments/pending': typeof AuthenticatedPaymentsPendingRoute
  '/payments/supplier': typeof AuthenticatedPaymentsSupplierRoute
  '/reports/bonus': typeof AuthenticatedReportsBonusRoute
  '/reports/cashflow': typeof AuthenticatedReportsCashflowRoute
  '/reports/expenses': typeof AuthenticatedReportsExpensesRoute
  '/reports/mutations': typeof AuthenticatedReportsMutationsRoute
  '/reports/payables': typeof AuthenticatedReportsPayablesRoute
  '/reports/receivables': typeof AuthenticatedReportsReceivablesRoute
  '/reports/returns': typeof AuthenticatedReportsReturnsRoute
  '/salary/accrual': typeof AuthenticatedSalaryAccrualRoute
  '/salary/accrual-kurir': typeof AuthenticatedSalaryAccrualKurirRoute
  '/salary/advance': typeof AuthenticatedSalaryAdvanceRoute
  '/salary/bonus': typeof AuthenticatedSalaryBonusRoute
  '/salary/bonus-pending': typeof AuthenticatedSalaryBonusPendingRoute
  '/salary/payment': typeof AuthenticatedSalaryPaymentRoute
  '/stock/in': typeof AuthenticatedStockInRoute
  '/stock/levels': typeof AuthenticatedStockLevelsRoute
  '/stock/mutations': typeof AuthenticatedStockMutationsRoute
  '/stock/pending': typeof AuthenticatedStockPendingRoute
  '/supplier/returns': typeof AuthenticatedSupplierReturnsRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/master/bank-accounts': typeof AuthenticatedMasterBankAccountsRoute
  '/master/customers': typeof AuthenticatedMasterCustomersRoute
  '/master/employees': typeof AuthenticatedMasterEmployeesRoute
  '/master/expense-categories': typeof AuthenticatedMasterExpenseCategoriesRoute
  '/master/products': typeof AuthenticatedMasterProductsRoute
  '/master/suppliers': typeof AuthenticatedMasterSuppliersRoute
  '/master/warehouses': typeof AuthenticatedMasterWarehousesRoute
  '/payments/customer': typeof AuthenticatedPaymentsCustomerRoute
  '/payments/pending': typeof AuthenticatedPaymentsPendingRoute
  '/payments/supplier': typeof AuthenticatedPaymentsSupplierRoute
  '/reports/bonus': typeof AuthenticatedReportsBonusRoute
  '/reports/cashflow': typeof AuthenticatedReportsCashflowRoute
  '/reports/expenses': typeof AuthenticatedReportsExpensesRoute
  '/reports/mutations': typeof AuthenticatedReportsMutationsRoute
  '/reports/payables': typeof AuthenticatedReportsPayablesRoute
  '/reports/receivables': typeof AuthenticatedReportsReceivablesRoute
  '/reports/returns': typeof AuthenticatedReportsReturnsRoute
  '/salary/accrual': typeof AuthenticatedSalaryAccrualRoute
  '/salary/accrual-kurir': typeof AuthenticatedSalaryAccrualKurirRoute
  '/salary/advance': typeof AuthenticatedSalaryAdvanceRoute
  '/salary/bonus': typeof AuthenticatedSalaryBonusRoute
  '/salary/bonus-pending': typeof AuthenticatedSalaryBonusPendingRoute
  '/salary/payment': typeof AuthenticatedSalaryPaymentRoute
  '/stock/in': typeof AuthenticatedStockInRoute
  '/stock/levels': typeof AuthenticatedStockLevelsRoute
  '/stock/mutations': typeof AuthenticatedStockMutationsRoute
  '/stock/pending': typeof AuthenticatedStockPendingRoute
  '/supplier/returns': typeof AuthenticatedSupplierReturnsRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/master/bank-accounts': typeof AuthenticatedMasterBankAccountsRoute
  '/_authenticated/master/customers': typeof AuthenticatedMasterCustomersRoute
  '/_authenticated/master/employees': typeof AuthenticatedMasterEmployeesRoute
  '/_authenticated/master/expense-categories': typeof AuthenticatedMasterExpenseCategoriesRoute
  '/_authenticated/master/products': typeof AuthenticatedMasterProductsRoute
  '/_authenticated/master/suppliers': typeof AuthenticatedMasterSuppliersRoute
  '/_authenticated/master/warehouses': typeof AuthenticatedMasterWarehousesRoute
  '/_authenticated/payments/customer': typeof AuthenticatedPaymentsCustomerRoute
  '/_authenticated/payments/pending': typeof AuthenticatedPaymentsPendingRoute
  '/_authenticated/payments/supplier': typeof AuthenticatedPaymentsSupplierRoute
  '/_authenticated/reports/bonus': typeof AuthenticatedReportsBonusRoute
  '/_authenticated/reports/cashflow': typeof AuthenticatedReportsCashflowRoute
  '/_authenticated/reports/expenses': typeof AuthenticatedReportsExpensesRoute
  '/_authenticated/reports/mutations': typeof AuthenticatedReportsMutationsRoute
  '/_authenticated/reports/payables': typeof AuthenticatedReportsPayablesRoute
  '/_authenticated/reports/receivables': typeof AuthenticatedReportsReceivablesRoute
  '/_authenticated/reports/returns': typeof AuthenticatedReportsReturnsRoute
  '/_authenticated/salary/accrual': typeof AuthenticatedSalaryAccrualRoute
  '/_authenticated/salary/accrual-kurir': typeof AuthenticatedSalaryAccrualKurirRoute
  '/_authenticated/salary/advance': typeof AuthenticatedSalaryAdvanceRoute
  '/_authenticated/salary/bonus': typeof AuthenticatedSalaryBonusRoute
  '/_authenticated/salary/bonus-pending': typeof AuthenticatedSalaryBonusPendingRoute
  '/_authenticated/salary/payment': typeof AuthenticatedSalaryPaymentRoute
  '/_authenticated/stock/in': typeof AuthenticatedStockInRoute
  '/_authenticated/stock/levels': typeof AuthenticatedStockLevelsRoute
  '/_authenticated/stock/mutations': typeof AuthenticatedStockMutationsRoute
  '/_authenticated/stock/pending': typeof AuthenticatedStockPendingRoute
  '/_authenticated/supplier/returns': typeof AuthenticatedSupplierReturnsRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/portal'
    | '/dashboard'
    | '/expenses'
    | '/sales'
    | '/settings'
    | '/master/bank-accounts'
    | '/master/customers'
    | '/master/employees'
    | '/master/expense-categories'
    | '/master/products'
    | '/master/suppliers'
    | '/master/warehouses'
    | '/payments/customer'
    | '/payments/pending'
    | '/payments/supplier'
    | '/reports/bonus'
    | '/reports/cashflow'
    | '/reports/expenses'
    | '/reports/mutations'
    | '/reports/payables'
    | '/reports/receivables'
    | '/reports/returns'
    | '/salary/accrual'
    | '/salary/accrual-kurir'
    | '/salary/advance'
    | '/salary/bonus'
    | '/salary/bonus-pending'
    | '/salary/payment'
    | '/stock/in'
    | '/stock/levels'
    | '/stock/mutations'
    | '/stock/pending'
    | '/supplier/returns'
    | '/api/public/bootstrap-admin'
    | '/api/public/telegram/webhook'
    | '/api/public/v1/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/portal'
    | '/dashboard'
    | '/expenses'
    | '/sales'
    | '/settings'
    | '/master/bank-accounts'
    | '/master/customers'
    | '/master/employees'
    | '/master/expense-categories'
    | '/master/products'
    | '/master/suppliers'
    | '/master/warehouses'
    | '/payments/customer'
    | '/payments/pending'
    | '/payments/supplier'
    | '/reports/bonus'
    | '/reports/cashflow'
    | '/reports/expenses'
    | '/reports/mutations'
    | '/reports/payables'
    | '/reports/receivables'
    | '/reports/returns'
    | '/salary/accrual'
    | '/salary/accrual-kurir'
    | '/salary/advance'
    | '/salary/bonus'
    | '/salary/bonus-pending'
    | '/salary/payment'
    | '/stock/in'
    | '/stock/levels'
    | '/stock/mutations'
    | '/stock/pending'
    | '/supplier/returns'
    | '/api/public/bootstrap-admin'
    | '/api/public/telegram/webhook'
    | '/api/public/v1/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/portal'
    | '/_authenticated/dashboard'
    | '/_authenticated/expenses'
    | '/_authenticated/sales'
    | '/_authenticated/settings'
    | '/_authenticated/master/bank-accounts'
    | '/_authenticated/master/customers'
    | '/_authenticated/master/employees'
    | '/_authenticated/master/expense-categories'
    | '/_authenticated/master/products'
    | '/_authenticated/master/suppliers'
    | '/_authenticated/master/warehouses'
    | '/_authenticated/payments/customer'
    | '/_authenticated/payments/pending'
    | '/_authenticated/payments/supplier'
    | '/_authenticated/reports/bonus'
    | '/_authenticated/reports/cashflow'
    | '/_authenticated/reports/expenses'
    | '/_authenticated/reports/mutations'
    | '/_authenticated/reports/payables'
    | '/_authenticated/reports/receivables'
    | '/_authenticated/reports/returns'
    | '/_authenticated/salary/accrual'
    | '/_authenticated/salary/accrual-kurir'
    | '/_authenticated/salary/advance'
    | '/_authenticated/salary/bonus'
    | '/_authenticated/salary/bonus-pending'
    | '/_authenticated/salary/payment'
    | '/_authenticated/stock/in'
    | '/_authenticated/stock/levels'
    | '/_authenticated/stock/mutations'
    | '/_authenticated/stock/pending'
    | '/_authenticated/supplier/returns'
    | '/api/public/bootstrap-admin'
    | '/api/public/telegram/webhook'
    | '/api/public/v1/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PortalRoute: typeof PortalRoute
  ApiPublicBootstrapAdminRoute: typeof ApiPublicBootstrapAdminRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  ApiPublicV1SplatRoute: typeof ApiPublicV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/bootstrap-admin': {
      id: '/api/public/bootstrap-admin'
      path: '/api/public/bootstrap-admin'
      fullPath: '/api/public/bootstrap-admin'
      preLoaderRoute: typeof ApiPublicBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/supplier/returns': {
      id: '/_authenticated/supplier/returns'
      path: '/supplier/returns'
      fullPath: '/supplier/returns'
      preLoaderRoute: typeof AuthenticatedSupplierReturnsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock/pending': {
      id: '/_authenticated/stock/pending'
      path: '/stock/pending'
      fullPath: '/stock/pending'
      preLoaderRoute: typeof AuthenticatedStockPendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock/mutations': {
      id: '/_authenticated/stock/mutations'
      path: '/stock/mutations'
      fullPath: '/stock/mutations'
      preLoaderRoute: typeof AuthenticatedStockMutationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock/levels': {
      id: '/_authenticated/stock/levels'
      path: '/stock/levels'
      fullPath: '/stock/levels'
      preLoaderRoute: typeof AuthenticatedStockLevelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock/in': {
      id: '/_authenticated/stock/in'
      path: '/stock/in'
      fullPath: '/stock/in'
      preLoaderRoute: typeof AuthenticatedStockInRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salary/payment': {
      id: '/_authenticated/salary/payment'
      path: '/salary/payment'
      fullPath: '/salary/payment'
      preLoaderRoute: typeof AuthenticatedSalaryPaymentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salary/bonus-pending': {
      id: '/_authenticated/salary/bonus-pending'
      path: '/salary/bonus-pending'
      fullPath: '/salary/bonus-pending'
      preLoaderRoute: typeof AuthenticatedSalaryBonusPendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salary/bonus': {
      id: '/_authenticated/salary/bonus'
      path: '/salary/bonus'
      fullPath: '/salary/bonus'
      preLoaderRoute: typeof AuthenticatedSalaryBonusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salary/advance': {
      id: '/_authenticated/salary/advance'
      path: '/salary/advance'
      fullPath: '/salary/advance'
      preLoaderRoute: typeof AuthenticatedSalaryAdvanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salary/accrual-kurir': {
      id: '/_authenticated/salary/accrual-kurir'
      path: '/salary/accrual-kurir'
      fullPath: '/salary/accrual-kurir'
      preLoaderRoute: typeof AuthenticatedSalaryAccrualKurirRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salary/accrual': {
      id: '/_authenticated/salary/accrual'
      path: '/salary/accrual'
      fullPath: '/salary/accrual'
      preLoaderRoute: typeof AuthenticatedSalaryAccrualRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/returns': {
      id: '/_authenticated/reports/returns'
      path: '/reports/returns'
      fullPath: '/reports/returns'
      preLoaderRoute: typeof AuthenticatedReportsReturnsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/receivables': {
      id: '/_authenticated/reports/receivables'
      path: '/reports/receivables'
      fullPath: '/reports/receivables'
      preLoaderRoute: typeof AuthenticatedReportsReceivablesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/payables': {
      id: '/_authenticated/reports/payables'
      path: '/reports/payables'
      fullPath: '/reports/payables'
      preLoaderRoute: typeof AuthenticatedReportsPayablesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/mutations': {
      id: '/_authenticated/reports/mutations'
      path: '/reports/mutations'
      fullPath: '/reports/mutations'
      preLoaderRoute: typeof AuthenticatedReportsMutationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/expenses': {
      id: '/_authenticated/reports/expenses'
      path: '/reports/expenses'
      fullPath: '/reports/expenses'
      preLoaderRoute: typeof AuthenticatedReportsExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/cashflow': {
      id: '/_authenticated/reports/cashflow'
      path: '/reports/cashflow'
      fullPath: '/reports/cashflow'
      preLoaderRoute: typeof AuthenticatedReportsCashflowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/bonus': {
      id: '/_authenticated/reports/bonus'
      path: '/reports/bonus'
      fullPath: '/reports/bonus'
      preLoaderRoute: typeof AuthenticatedReportsBonusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments/supplier': {
      id: '/_authenticated/payments/supplier'
      path: '/payments/supplier'
      fullPath: '/payments/supplier'
      preLoaderRoute: typeof AuthenticatedPaymentsSupplierRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments/pending': {
      id: '/_authenticated/payments/pending'
      path: '/payments/pending'
      fullPath: '/payments/pending'
      preLoaderRoute: typeof AuthenticatedPaymentsPendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments/customer': {
      id: '/_authenticated/payments/customer'
      path: '/payments/customer'
      fullPath: '/payments/customer'
      preLoaderRoute: typeof AuthenticatedPaymentsCustomerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master/warehouses': {
      id: '/_authenticated/master/warehouses'
      path: '/master/warehouses'
      fullPath: '/master/warehouses'
      preLoaderRoute: typeof AuthenticatedMasterWarehousesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master/suppliers': {
      id: '/_authenticated/master/suppliers'
      path: '/master/suppliers'
      fullPath: '/master/suppliers'
      preLoaderRoute: typeof AuthenticatedMasterSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master/products': {
      id: '/_authenticated/master/products'
      path: '/master/products'
      fullPath: '/master/products'
      preLoaderRoute: typeof AuthenticatedMasterProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master/expense-categories': {
      id: '/_authenticated/master/expense-categories'
      path: '/master/expense-categories'
      fullPath: '/master/expense-categories'
      preLoaderRoute: typeof AuthenticatedMasterExpenseCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master/employees': {
      id: '/_authenticated/master/employees'
      path: '/master/employees'
      fullPath: '/master/employees'
      preLoaderRoute: typeof AuthenticatedMasterEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master/customers': {
      id: '/_authenticated/master/customers'
      path: '/master/customers'
      fullPath: '/master/customers'
      preLoaderRoute: typeof AuthenticatedMasterCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master/bank-accounts': {
      id: '/_authenticated/master/bank-accounts'
      path: '/master/bank-accounts'
      fullPath: '/master/bank-accounts'
      preLoaderRoute: typeof AuthenticatedMasterBankAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/v1/$': {
      id: '/api/public/v1/$'
      path: '/api/public/v1/$'
      fullPath: '/api/public/v1/$'
      preLoaderRoute: typeof ApiPublicV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedMasterBankAccountsRoute: typeof AuthenticatedMasterBankAccountsRoute
  AuthenticatedMasterCustomersRoute: typeof AuthenticatedMasterCustomersRoute
  AuthenticatedMasterEmployeesRoute: typeof AuthenticatedMasterEmployeesRoute
  AuthenticatedMasterExpenseCategoriesRoute: typeof AuthenticatedMasterExpenseCategoriesRoute
  AuthenticatedMasterProductsRoute: typeof AuthenticatedMasterProductsRoute
  AuthenticatedMasterSuppliersRoute: typeof AuthenticatedMasterSuppliersRoute
  AuthenticatedMasterWarehousesRoute: typeof AuthenticatedMasterWarehousesRoute
  AuthenticatedPaymentsCustomerRoute: typeof AuthenticatedPaymentsCustomerRoute
  AuthenticatedPaymentsPendingRoute: typeof AuthenticatedPaymentsPendingRoute
  AuthenticatedPaymentsSupplierRoute: typeof AuthenticatedPaymentsSupplierRoute
  AuthenticatedReportsBonusRoute: typeof AuthenticatedReportsBonusRoute
  AuthenticatedReportsCashflowRoute: typeof AuthenticatedReportsCashflowRoute
  AuthenticatedReportsExpensesRoute: typeof AuthenticatedReportsExpensesRoute
  AuthenticatedReportsMutationsRoute: typeof AuthenticatedReportsMutationsRoute
  AuthenticatedReportsPayablesRoute: typeof AuthenticatedReportsPayablesRoute
  AuthenticatedReportsReceivablesRoute: typeof AuthenticatedReportsReceivablesRoute
  AuthenticatedReportsReturnsRoute: typeof AuthenticatedReportsReturnsRoute
  AuthenticatedSalaryAccrualRoute: typeof AuthenticatedSalaryAccrualRoute
  AuthenticatedSalaryAccrualKurirRoute: typeof AuthenticatedSalaryAccrualKurirRoute
  AuthenticatedSalaryAdvanceRoute: typeof AuthenticatedSalaryAdvanceRoute
  AuthenticatedSalaryBonusRoute: typeof AuthenticatedSalaryBonusRoute
  AuthenticatedSalaryBonusPendingRoute: typeof AuthenticatedSalaryBonusPendingRoute
  AuthenticatedSalaryPaymentRoute: typeof AuthenticatedSalaryPaymentRoute
  AuthenticatedStockInRoute: typeof AuthenticatedStockInRoute
  AuthenticatedStockLevelsRoute: typeof AuthenticatedStockLevelsRoute
  AuthenticatedStockMutationsRoute: typeof AuthenticatedStockMutationsRoute
  AuthenticatedStockPendingRoute: typeof AuthenticatedStockPendingRoute
  AuthenticatedSupplierReturnsRoute: typeof AuthenticatedSupplierReturnsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedMasterBankAccountsRoute: AuthenticatedMasterBankAccountsRoute,
  AuthenticatedMasterCustomersRoute: AuthenticatedMasterCustomersRoute,
  AuthenticatedMasterEmployeesRoute: AuthenticatedMasterEmployeesRoute,
  AuthenticatedMasterExpenseCategoriesRoute:
    AuthenticatedMasterExpenseCategoriesRoute,
  AuthenticatedMasterProductsRoute: AuthenticatedMasterProductsRoute,
  AuthenticatedMasterSuppliersRoute: AuthenticatedMasterSuppliersRoute,
  AuthenticatedMasterWarehousesRoute: AuthenticatedMasterWarehousesRoute,
  AuthenticatedPaymentsCustomerRoute: AuthenticatedPaymentsCustomerRoute,
  AuthenticatedPaymentsPendingRoute: AuthenticatedPaymentsPendingRoute,
  AuthenticatedPaymentsSupplierRoute: AuthenticatedPaymentsSupplierRoute,
  AuthenticatedReportsBonusRoute: AuthenticatedReportsBonusRoute,
  AuthenticatedReportsCashflowRoute: AuthenticatedReportsCashflowRoute,
  AuthenticatedReportsExpensesRoute: AuthenticatedReportsExpensesRoute,
  AuthenticatedReportsMutationsRoute: AuthenticatedReportsMutationsRoute,
  AuthenticatedReportsPayablesRoute: AuthenticatedReportsPayablesRoute,
  AuthenticatedReportsReceivablesRoute: AuthenticatedReportsReceivablesRoute,
  AuthenticatedReportsReturnsRoute: AuthenticatedReportsReturnsRoute,
  AuthenticatedSalaryAccrualRoute: AuthenticatedSalaryAccrualRoute,
  AuthenticatedSalaryAccrualKurirRoute: AuthenticatedSalaryAccrualKurirRoute,
  AuthenticatedSalaryAdvanceRoute: AuthenticatedSalaryAdvanceRoute,
  AuthenticatedSalaryBonusRoute: AuthenticatedSalaryBonusRoute,
  AuthenticatedSalaryBonusPendingRoute: AuthenticatedSalaryBonusPendingRoute,
  AuthenticatedSalaryPaymentRoute: AuthenticatedSalaryPaymentRoute,
  AuthenticatedStockInRoute: AuthenticatedStockInRoute,
  AuthenticatedStockLevelsRoute: AuthenticatedStockLevelsRoute,
  AuthenticatedStockMutationsRoute: AuthenticatedStockMutationsRoute,
  AuthenticatedStockPendingRoute: AuthenticatedStockPendingRoute,
  AuthenticatedSupplierReturnsRoute: AuthenticatedSupplierReturnsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PortalRoute: PortalRoute,
  ApiPublicBootstrapAdminRoute: ApiPublicBootstrapAdminRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  ApiPublicV1SplatRoute: ApiPublicV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
